name: Step Level Var and Secret

on: workflow_dispatch

jobs:
  connect-db-job:
    name: Simulate Database Connection
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Mysql DB
      env:
        DB_USER:  ${{ secrets.MY_DB_USER }}
        DB_PASS:  ${{ secrets.MY_DB_PASSWORD }}

      run: |
        echo "Connection with User: $DB_USER"
        echo "Authentication with Pass: $DB_PASS"
        echo "Connection to MySQL Database successfully"
        
