name: 01 - Hello World Workflow

on: workflow_dispatch

jobs:
    hello-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print Welcome Message
              run: |
                echo "Welcome to Github Actions Hands-on"
                echo "Repository: demo-github-project"
                echo "Triggered manually by users"


