name: 03 - Variables and Secrets Demo

on: workflow_dispatch

env:
    GLOBAL_VAR: "Learning GitHub Actions"
  
jobs:
    print-vars:
        runs-on: ubuntu-latest
        env:
          JOB_VAR: "Inside Job Level"
        steps: 
            - name: Print Variables and Contexts
              run: |
                echo "Global Variable: ${{ env.GLOBAL_VAR }}"
                echo "Job Variable: ${{ env.JOB_VAR }}"
                echo "Triggered By User: ${{ github.actor }}"
                echo "Current Commit SHA: ${{ github.sha }}"

