name: 04 - Sample Variable WorkFlow

on: workflow_dispatch

env:
    GLOBAL_VAR: "This is the purpose of Github Learning"

jobs:
    Sample_Variable_Workflow:
        runs-on: ubuntu-latest
        env:
            JOB_VAR: "Keep Learning"
        run:
           echo "${{ env.GLOBAL_VAR }}"

        run:
            echo "${{ env.JOB_VAR }}" 
