name: Day02 Vars and Secrets Lab

on: workflow_dispatch

env:
  APP_ENV: "Staging"
  APP_PORT: "8000"

jobs:
  test-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Print Normal Environment Variables
        run:  |
          echo "Current Environment: ${{ env.APP_ENV }}"
          echo "App Running Port: ${{ env.APP_PORT }}"

      - name: Print Encrypted Secret
        env:
          DB_PASS: ${{ secrets.MY_DB_PASSWORD }}
        run:  |
          echo "Connection to Database...."
          echo "Database Password is: $DB_PASS"
        
