name: Day02 Vars and Secrets

on: workflow_dispatch

jobs:
  connect-db-job:
    name: Simulate Database Connection
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Mysql DB
        env:
          DB_USER: ${{ secrets.MY_DB_USER }}
          DB_PASS: ${{ secret.MY_DB_PASSWORD }}
        run: |
          echo "Connection With User: $DB_USER"
          echo "Authentication With Pass: $DB_PASS"
          echo "Connection to MYSQL Database Successfully"
